# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "38s4f3id97wsb0rg9nm9zvxyq0nvwrmrpa5dzvrkp36mf5ibs98b4z6lvsbrwzzs0sbcank6c7gpp06vcwp9acfhp41rzlhi3ybsxwy";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "acorn-5.5.3" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.5.3.tgz";
        sha512 = "0wmwifv9mm9gqcir9zbz5y1gl1rgwwprqh1f3csjydj8kf3byca7img3rh5b54kbnw3ik34bc6ynbnzsd01zmxrsfdvjv95hn84rpld";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "ajv-keywords-2.1.1" = {
      name = "ajv-keywords";
      packageName = "ajv-keywords";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-2.1.1.tgz";
        sha1 = "617997fc5f60576894c435f940d819e135b80762";
      };
    };
    "ansi-escapes-3.1.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-3.1.0.tgz";
        sha512 = "1bm72rs09dwjhfif8kqjxnpb5fgmcdgkn5483f11j6791s5161f2kvxy69pkgcq0jdws6kqfmr1bx5189lnvkzgkq851qs3gzq1n02j";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "2lgkskkj4c1fsnrksy0yffda0wss84p8lfiazdc7jli7iqnvrxkzbxjzpvx13lm28qw0zkawfxvz2bdiisc72ccy7hx8i8rm4iijgam";
      };
    };
    "aproba-1.2.0" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
        sha512 = "13mgnbmdhdq0qncijvpip1l39q1a8labcvj3hc3n1yl2zch106mdkn7p7bd5knvmfkkn1js9nd47nzyjk1himbm8ry8i8gd6mk7mlk3";
      };
    };
    "are-we-there-yet-1.1.4" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.4.tgz";
        sha1 = "bb5dca382bb94f05e15194373d16fd3ba1ca110d";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "17fhywmdjcp8g0ys089i5xg26yajkkg9zg8hyry3fghz75b2pq5vdx997dk5p2sc15r9nsj8rmf4f27g81hi92kzj5q86sdmg5ni553";
      };
    };
    "array-union-1.0.2" = {
      name = "array-union";
      packageName = "array-union";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz";
        sha1 = "9a34410e4f4e3da23dea375be5be70f24778ec39";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "arrify-1.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
        sha1 = "898508da2226f380df904728456849c1501a4b0d";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.7.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.7.0.tgz";
        sha512 = "3rkdcpm3myysvq9nj6plgvpngzsbv7qk1wvb9f4m3gcsl23pf5x0hyph02svyl2v1lgjji8kl75ii7q04lhhhgjyw1irbinmxsl6qyz";
      };
    };
    "babel-code-frame-6.26.0" = {
      name = "babel-code-frame";
      packageName = "babel-code-frame";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.26.0.tgz";
        sha1 = "63fd43f7dc1e3bb7ce35947db8fe369a3f58c74b";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.2.3" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.3.tgz";
        sha512 = "3kqp8hzql2ccdqf7vqizav1lrwp5gynn081718g9slxcs428sv02n037xb9hfgrqybbk4qacnk5mcv63z8fm3l4h6fi06xm8nqj3h1j";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha512 = "19h20yqpvca08dns1rs4f057f10w63v0snxfml4h5khsk266x3x1im0w72bza4k2xn0kfz6jlv001dhcvxsjr09bmbqnysils9m7437";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "248cnpbbf0p32h53rd3g8wzpgrkaj4p078ra1g6l16f82i6bzkvmhwqan5rk88apbll9ly1476kngd7f7z27i3b3zxpbb3064f8yaw8";
      };
    };
    "browser-stdout-1.3.1" = {
      name = "browser-stdout";
      packageName = "browser-stdout";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-stdout/-/browser-stdout-1.3.1.tgz";
        sha512 = "21jjhrf3wdmzsfqgva5s7shs1wdmcdxsjvi75p8z7i0q2i6n3654gpxjqlhbnpmzm25cpkshyi8swy13017qkp9m7xnbgw0bwiia45a";
      };
    };
    "buffer-from-1.0.0" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.0.0.tgz";
        sha512 = "3252laq8prm41lgzlhmc7rdj99gwcvpf7cn6j686g4qmspnl3haid5khv9pc9cfjja9wb64nwfvgdwi2kpdf125xfg48aqapwssjxpk";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "builtins-1.0.3" = {
      name = "builtins";
      packageName = "builtins";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-1.0.3.tgz";
        sha1 = "cb94faeb61c8696451db36534e1422f94f0aee88";
      };
    };
    "caller-path-0.1.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-0.1.0.tgz";
        sha1 = "94085ef63581ecd3daa92444a8fe94e82577751f";
      };
    };
    "callsites-0.2.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-0.2.0.tgz";
        sha1 = "afab96262910a7f33c19a5775825c69f34e350ca";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.3.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.3.2.tgz";
        sha512 = "06jlrzx0nb92910rcfhx55n28jgvhc0qda49scnfyifnmc31dyfqsl5qqiwhsxkrhrc6c07x69q037f1pwg06kkfd1qdzaxz7dj7kk4";
      };
    };
    "chardet-0.4.2" = {
      name = "chardet";
      packageName = "chardet";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chardet/-/chardet-0.4.2.tgz";
        sha1 = "b5473b33dc97c424e5d98dc87d55d4d8a29c8bf2";
      };
    };
    "circular-json-0.3.3" = {
      name = "circular-json";
      packageName = "circular-json";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/circular-json/-/circular-json-0.3.3.tgz";
        sha512 = "3hadrrn41znfv3gbqjxf0ckzjmns7w7zgsqw73sdz8nclaff9b0cg1mqhz3zxw3ndnmqqvrdcfykkfpv2v1pv4jdyzcccbn3hsbg4ji";
      };
    };
    "cli-cursor-2.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-2.1.0.tgz";
        sha1 = "b35dac376479facc3e94747d41d0d0f5238ffcb5";
      };
    };
    "cli-width-2.2.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-2.2.0.tgz";
        sha1 = "ff19ede8a9a5e579324147b0c11f0fbcbabed639";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "color-convert-1.9.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.1.tgz";
        sha512 = "32rj1090g95xcvm0d2ya6jbqdhiy9w2wv3picdy33fzrm455v0gi7g4n8lw0n31g37wwbdnz7lxjsisgbsaqz1d10j9nh5hi2f9lccs";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "commander-2.11.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.11.0.tgz";
        sha512 = "2yi2hwf0bghfnv1fdgd4wvh7s0acjrgqbgww97ncm6i6s6ffs1zahnj48f6gqpqj6fsf0jigvnr0civ25k2160c38281r80wvg7jkkg";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "05nnf80j9ls12y3cw2dfnc6rmand3ya5sx9cqn9dgg19ljzdnyfjjv8ig79xi73gr2y4rkfzn9wjip2zzwp5n2d49njd3ki2a1c3cfv";
      };
    };
    "config-chain-1.1.11" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.11.tgz";
        sha1 = "aba09747dfbe4c3e70e766a6e41586e1859fc6f2";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "del-2.2.2" = {
      name = "del";
      packageName = "del";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/del/-/del-2.2.2.tgz";
        sha1 = "c12c981d067846c84bcaf862cff930d907ffd1a8";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "diff-3.5.0" = {
      name = "diff";
      packageName = "diff";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-3.5.0.tgz";
        sha512 = "32bkv3cfhax4x5zhiyfn63wjhqwkzsjiql3my8p3d9hvv020p8f9hdi7mpqixrkpgs0g9k15mn736s449yad9wq1plhxyhxb2sam3h3";
      };
    };
    "doctrine-2.1.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-2.1.0.tgz";
        sha512 = "0iz6zh5d0kqs0ndd1ydsj4vaf2x3k3p0k5a7b75gsbhkqaqqq93dgsa2bpifvw7svck2sndd21mv7mp60q111rbghpssp0rxs9956fz";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "eslint-scope-3.7.1" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-3.7.1.tgz";
        sha1 = "3d63c3edfda02e06e01a452ad88caacc7cdcb6e8";
      };
    };
    "eslint-visitor-keys-1.0.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-1.0.0.tgz";
        sha512 = "02hr99x8cnc80p9hn5si7mngqpzvvjkxmdv8sch68z0qpqwjdlx3j1w6d9rhr6wgcnqf1mrxyji8wvfddbf7xr13z2nzihv29gvyfdb";
      };
    };
    "espree-3.5.4" = {
      name = "espree";
      packageName = "espree";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.5.4.tgz";
        sha512 = "3a07jjjp8g8mdayw3n9l0p0llw7cfipjifan2ccyn2vm1zyafrmv5cj11rc6qmk7ibbq1vc4xxc3sfr54qpgxmxiizj0ck63d1hh1y8";
      };
    };
    "esprima-4.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.0.tgz";
        sha512 = "27mkhd94y9vrr8pb97br0ym5h85rawwb0biswgwdfp31x0387y12k9p9598bi4fc83fif6crfzqiqmmjs4x7gcb22ml3z1fldqm7yx1";
      };
    };
    "esquery-1.0.1" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.0.1.tgz";
        sha512 = "0s9lxfan3qbvpprj71ldy70x9sz4xkpakhr3pymkm13bx40px4kp4xcgipscn8m21qigddin5mkr52bicbm34g46dapyn68kikv4s2a";
      };
    };
    "esrecurse-4.2.1" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.2.1.tgz";
        sha512 = "06zyknk70y80n428x20wvjqy5822wgz2yaxzw387njnz3ar6ixzjcxzr2jsl8wrm0m9jpa4ysbcr9znpk6gbkqd7wby084zxw3l317b";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "external-editor-2.2.0" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-2.2.0.tgz";
        sha512 = "3sf897ajmkcp0j6rgd0jy6k95s9ck3j305yrr00kmckl8qdhswhbdd5g4m2fai03x8phs1vw2ahf9v7ym5ji4zfxydxyamiy61glabd";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "figures-2.0.0" = {
      name = "figures";
      packageName = "figures";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-2.0.0.tgz";
        sha1 = "3ab1a2d2a62c8bfb431a0c94cb797a2fce27c962";
      };
    };
    "file-entry-cache-2.0.0" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-2.0.0.tgz";
        sha1 = "c392990c3e684783d838b8c84a45d8a048458361";
      };
    };
    "findit-2.0.0" = {
      name = "findit";
      packageName = "findit";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findit/-/findit-2.0.0.tgz";
        sha1 = "6509f0126af4c178551cfa99394e032e13a4d56e";
      };
    };
    "flat-cache-1.3.0" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-1.3.0.tgz";
        sha1 = "d3030b32b38154f4e3b7e9c709f490f7ef97c481";
      };
    };
    "foreachasync-3.0.0" = {
      name = "foreachasync";
      packageName = "foreachasync";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreachasync/-/foreachasync-3.0.0.tgz";
        sha1 = "5502987dc8714be3392097f32e0071c9dee07cf6";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "fs-extra-0.6.4" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-0.6.4.tgz";
        sha1 = "f46f0c75b7841f8d200b3348cd4d691d5a099d15";
      };
    };
    "fs.extra-1.3.2" = {
      name = "fs.extra";
      packageName = "fs.extra";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.extra/-/fs.extra-1.3.2.tgz";
        sha1 = "dd023f93013bee24531f1b33514c37b20fd93349";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "functional-red-black-tree-1.0.1" = {
      name = "functional-red-black-tree";
      packageName = "functional-red-black-tree";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz";
        sha1 = "1b0ab3bd553b2a0d6399d29c0e3ea0b252078327";
      };
    };
    "gauge-2.7.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "2c03405c7538c39d7eb37b317022e325fb018bf7";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "globals-11.4.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.4.0.tgz";
        sha512 = "0fgjya5jfxjd8gzgpnpig973bbplfq2i5fkfpi5lxyjsi3988wq3by19ka2ql2j4a80l9bk5g5brq4vvd2hr61ak79pzwm5z24ycb0g";
      };
    };
    "globby-5.0.0" = {
      name = "globby";
      packageName = "globby";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-5.0.0.tgz";
        sha1 = "ebd84667ca0dbb330b99bcfc68eac2bc54370e0d";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "growl-1.10.3" = {
      name = "growl";
      packageName = "growl";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/growl/-/growl-1.10.3.tgz";
        sha512 = "3aibvz85l13j140w4jjdk8939q6r7dnf8ay2licxgkaaldk7wbm093c1p5g7k5cg80rl0xslmczyraawfgdr82hhxn7rfsm1rn6rac4";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-2.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz";
        sha1 = "e8207af1cc7b30d446cc70b734b5e8be18f88d51";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha512 = "1nl2hjr2mnhj5jlaz8mh54z7acwz5j5idkch04qgjk78756gw5d0fjk4a2immil5ij9ijdssb9ndpryvnh2xpcbgcjv8lxybn330als";
      };
    };
    "he-1.1.1" = {
      name = "he";
      packageName = "he";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.1.1.tgz";
        sha1 = "93410fd21b009735151f8868c2f271f3427e23fd";
      };
    };
    "hoek-4.2.1" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.1.tgz";
        sha512 = "1y8kprb3qldxqj31zai5n8dvhydsl9nn5w4rskhnbzzhldn6pm6n5lcyam3sfkb61a62d5m58k8im7z6ngwbd9cw9zp4zm4y7ckrf20";
      };
    };
    "hosted-git-info-2.6.0" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.6.0.tgz";
        sha512 = "1vi4baj130s7mladvb4rad9ka8nqzcwws9i1zaaplp0fdrmnfwjfbpq01cghha2c2frd2f900f07awglhbbyym0bpwmrph0hhhf11ll";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "iconv-lite-0.4.21" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.21.tgz";
        sha512 = "0myjcmxx7dn5liikg8d2zgwb433sk761dfxwwnszyam16rzv5dzva352jrvav7cnambn0ha8fzh6g6xhdhxsd20l5v1p65r6vvmazhj";
      };
    };
    "ignore-3.3.7" = {
      name = "ignore";
      packageName = "ignore";
      version = "3.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-3.3.7.tgz";
        sha512 = "0f6xhxww989yic6hwdm8mbylcyakfkrrn22a39wdcc9k842xxyyhzfxkmi79s9gjk3rp3h07n265lf4n51z8yafpdm78d617dxbfqb0";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ini-1.3.5" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
        sha512 = "1rjbvf1rg5ywhnba08sgagn2qf23lab330qrqmh7d891zap3xpxcyfyj1cblpf0f0rypglcfacybzyrpd4996aa1mbc820awa33k5j5";
      };
    };
    "inquirer-3.3.0" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-3.3.0.tgz";
        sha512 = "1wsmzzva3rfjb4bfks7ba2nvha9ziwgq2kag6xxibc5cc6mz19xbgj4fm3a7ghvfbfx4am0x13ibc8j2s5m3sv12nph44rq56gnvv47";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "is-path-cwd-1.0.0" = {
      name = "is-path-cwd";
      packageName = "is-path-cwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-cwd/-/is-path-cwd-1.0.0.tgz";
        sha1 = "d225ec23132e89edd38fda767472e62e65f1106d";
      };
    };
    "is-path-in-cwd-1.0.1" = {
      name = "is-path-in-cwd";
      packageName = "is-path-in-cwd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-in-cwd/-/is-path-in-cwd-1.0.1.tgz";
        sha512 = "1lrmbdvciajn2smq4j80qvp3gpkkzqddiyay3xgbzni3gi4vljkawyyw68i6h8m1jfdg4jy8l8c16rlfvr17pnfb314xw5q6m2pad8n";
      };
    };
    "is-path-inside-1.0.1" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.1.tgz";
        sha1 = "8ef5b7de50437a3fdca6b4e865ef7aa55cb48036";
      };
    };
    "is-promise-2.1.0" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz";
        sha1 = "79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa";
      };
    };
    "is-resolvable-1.1.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.1.0.tgz";
        sha512 = "0r8v3dkj5qbfh2wlj4w1msyqsw6j5myvxi88wkw36isscb97yyc2yc1pwm64djrmh1css6jp9p08cx1zb479fg4gv26prciaifdh05a";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "js-yaml-3.11.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.11.0.tgz";
        sha512 = "0gka65n4d9gmcy0c8cy5h55r273dbxnw54gibp2nq5mmdmksjgb2nhcdfgfxs1wg3yayyrydn2v79fny7hdyq907dg87vmgjnsnr8mi";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha1 = "9db7b59496ad3f3cfef30a75142d2d930ad72651";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonfile-1.0.1" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-1.0.1.tgz";
        sha1 = "ea5efe40b83690b98667614a7392fc60e842c0dd";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "lru-cache-4.1.2" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.2.tgz";
        sha512 = "1whynbvy3pbwcpkxk6rqhsymj2h3bh7p13nfhs9ch6hfx96vrh86j7vd4lqcaqjy5dhsfjps6sh2wqndh269wjz42khbh6339g9a1y2";
      };
    };
    "mime-db-1.33.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.33.0.tgz";
        sha512 = "36xnw59ik9fqym00cmwb5nyzg0l03k70cp413f7639j93wgmzk1mh0xjc7i6zz3r6k9xnwh0g5cm5a1f3y8c6plgy4qld7fm887ywh4";
      };
    };
    "mime-types-2.1.18" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.18.tgz";
        sha512 = "22krj1kw7n9z10zdyx7smcaim4bzwqsqzhspwha06q58gcrxfp93hw2cd0vk5crhq5p2dwzqlpacg32lrmp5sjzb798zdzy35mdmkwm";
      };
    };
    "mimic-fn-1.2.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-1.2.0.tgz";
        sha512 = "1clrrqw75rmpkw0x53axy8va2hq2gzynz9zb58m0xv1nh3lg81cv4dfdy7pk9vrlb9ydwmj6klpicwkv2bjx3m8aj4fi2ph3jxkizwd";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minipass-2.2.4" = {
      name = "minipass";
      packageName = "minipass";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-2.2.4.tgz";
        sha512 = "3r74gps1yd2fabj46qd42hknvpkg4aqwg3cdz8xjn8aqww0rsk3nmbgh8p2h0rkjlpxihg1wnpfa4bmpgmnydlbhpb1rz5dcxcwhdc7";
      };
    };
    "minizlib-1.1.0" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-1.1.0.tgz";
        sha512 = "2agpbdf9h90nhafdam3jwrw8gcz3jw1i40cx6bhwaw8qaf2s863gi2b77l73dc3hmf5dx491hv5km1rqzabgsbpkjxrvdcwy6pr8gp1";
      };
    };
    "mkdirp-0.3.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz";
        sha1 = "de3e5f8961c88c787ee1368df849ac4413eca8d7";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "ncp-0.4.2" = {
      name = "ncp";
      packageName = "ncp";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz";
        sha1 = "abcc6cbd3ec2ed2a729ff6e7c1fa8f01784a8574";
      };
    };
    "nijs-0.0.25" = {
      name = "nijs";
      packageName = "nijs";
      version = "0.0.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/nijs/-/nijs-0.0.25.tgz";
        sha1 = "04b035cb530d46859d1018839a518c029133f676";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "normalize-package-data-2.4.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.4.0.tgz";
        sha512 = "01wzws79ps84ylshjb7rfpjykgiqxnpr89s52p2yyzfx8nfvyh5flvf1almiiavsi75xgi8g3s5davc1mmgz7gn8yvlqz6gnhax8f7n";
      };
    };
    "npm-package-arg-6.1.0" = {
      name = "npm-package-arg";
      packageName = "npm-package-arg";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-6.1.0.tgz";
        sha512 = "14dqycy588sf0k73livvvpmp1dqmbhacc97pq3ksxk1wrm9j82r7hhlrxigj0nb58gz4cbvbh3isj1x3sjiqxs60dhv439xd4zy31nd";
      };
    };
    "npm-registry-client-8.5.1" = {
      name = "npm-registry-client";
      packageName = "npm-registry-client";
      version = "8.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-registry-client/-/npm-registry-client-8.5.1.tgz";
        sha512 = "0g7abpykfqb1x17pajm1ndsh61n3ydyimv5npsjrn9hd1s72csxh7fzdn28gldz30n00wgb8rg9y8jfhxli3cnii61i5vl0cwbwdf7f";
      };
    };
    "npmconf-2.1.2" = {
      name = "npmconf";
      packageName = "npmconf";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmconf/-/npmconf-2.1.2.tgz";
        sha1 = "66606a4a736f1e77a059aa071a79c94ab781853a";
      };
    };
    "npmlog-4.1.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
        sha512 = "2967mavp7zw0aawf5fadqf4pmn7vy5gya1yx2s9wwppvivhd9q4mpdnszfqvd7p6yks649bwbpj8iviw86g0hpp4f93d5ca7dmjmrfs";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-2.0.1" = {
      name = "onetime";
      packageName = "onetime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-2.0.1.tgz";
        sha1 = "067428230fd67443b2794b22bba528b6867962d4";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "osenv-0.1.5" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "3ddw0y41pxv08ls5xhmq1bi81hppjbr45k78cjfx99vznh5znrj5g1b1wab9caj1mqlsvmfms0zm9cfb47ygm0d8wv5fccx8049q9fh";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-is-inside-1.0.2" = {
      name = "path-is-inside";
      packageName = "path-is-inside";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-inside/-/path-is-inside-1.0.2.tgz";
        sha1 = "365417dede44430d1c11af61027facf074bdfc53";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "pluralize-7.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-7.0.0.tgz";
        sha512 = "2ihaln20qjx82jx73wgzirbyp8mfmhxr75am1h0w8n5hy2gsbgvw9dricv7h57ycxzax84bma96wjscmdszs5mr2lsyxpfjvhwl2601";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "0rw8xpqqkhs91722slvzf8icxfaimqp4w8zb3840jxr7r8n8035byl6dhdi5bm0yr6x7sdws0gf3m025fg6hqgaklwlbl4d7bah5l9j";
      };
    };
    "progress-2.0.0" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.0.tgz";
        sha1 = "8a1be366bf8fc23db2bd23f10c6fe920b4389d1f";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "0mj9b6190amln9rg89x5pq2n195s3v0gzicpdamv1kbabg69aw5m71l34jsjn7bqil7405l6l35x9ijnb3h4jz5vx2i00l8sl1ll2xm";
      };
    };
    "regexpp-1.1.0" = {
      name = "regexpp";
      packageName = "regexpp";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpp/-/regexpp-1.1.0.tgz";
        sha512 = "21xg69jgy5r7mffh5gjaqsv6izqvqh466q3fanmnzsgk33xhxp68nnszw4jcxk2w8lnc92phy26sr7xqq3ni36mg9yh2xb0bbqg1qrc";
      };
    };
    "request-2.85.0" = {
      name = "request";
      packageName = "request";
      version = "2.85.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.85.0.tgz";
        sha512 = "2d3hg10zs5ycnr8prmiwdhacf88fl0x0bi6szs0z2r07zcbk419laixwpjp8sqapbc2ifyyih7p3r60wgr58bmcncz3pqnx523c8zph";
      };
    };
    "require-uncached-1.0.3" = {
      name = "require-uncached";
      packageName = "require-uncached";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-uncached/-/require-uncached-1.0.3.tgz";
        sha1 = "4e0d56d6c9662fd31e43011c4b95aa49955421d3";
      };
    };
    "resolve-from-1.0.1" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-1.0.1.tgz";
        sha1 = "26cbfe935d1aeeeabb29bc3fe5aeb01e93d44226";
      };
    };
    "restore-cursor-2.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-2.0.0.tgz";
        sha1 = "9f7ee287f82fd326d4fd162923d62129eee0dfaf";
      };
    };
    "retry-0.10.1" = {
      name = "retry";
      packageName = "retry";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.10.1.tgz";
        sha1 = "e76388d217992c252750241d3d3956fed98d8ff4";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "run-async-2.3.0" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.3.0.tgz";
        sha1 = "0371ab4ae0bdd720d4166d7dfda64ff7a445a6c0";
      };
    };
    "rx-lite-4.0.8" = {
      name = "rx-lite";
      packageName = "rx-lite";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx-lite/-/rx-lite-4.0.8.tgz";
        sha1 = "0b1e11af8bc44836f04a6407e92da42467b79444";
      };
    };
    "rx-lite-aggregates-4.0.8" = {
      name = "rx-lite-aggregates";
      packageName = "rx-lite-aggregates";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx-lite-aggregates/-/rx-lite-aggregates-4.0.8.tgz";
        sha1 = "753b87a89a11c95467c4ac1626c4efc4e05c67be";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "2v99f22kh56y72d3s8wrgdvf5n10ry40dh3fwnsxr4d5rfvxdfxfmc3qyqkscnj4f8799jy9bpg6cm21x2d811dr9ib83wjrlmkg6k1";
      };
    };
    "semver-4.3.6" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.6.tgz";
        sha1 = "300bc6e0e86374f7ba61068b5b1ecd57fc6532da";
      };
    };
    "semver-5.5.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.0.tgz";
        sha512 = "0h32zh035y8m6dzcqhcymbhwgmc8839fa1hhj0jfh9ivp9kmqfj1sbwnsnkzcn9qm3sqn38sa8ys2g4c638lpnmzjr0a0qndmv7f8p1";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "slice-ansi-1.0.0" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-1.0.0.tgz";
        sha512 = "1xd3zsk02nck4y601rn98n8cicrphaw5bdix278mk1yizmjv9s0wpa6akcqggd7d99c55s3byf4ylqdxkshyfsfnfx7lvwbmq2b3siw";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "sntp-2.1.0" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz";
        sha512 = "0k2smmr24w5hb1cpql6vcgh58vzp4pmh9anf0bgz3arlsgq1mapnlq9fjqr6xs10aq1cmxaw987fwknqi62frax0fvs9bj3q3kmpg8l";
      };
    };
    "spdx-correct-3.0.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.0.0.tgz";
        sha512 = "3xgkqk4hsm4nzvy68icv1rlv4s0qgb7mwpi9s4z2mp1a5fwny6kc6m4nqa7zzx2k7mrjlh7psci9lb7892bl3q4r4y2f4sw7vvnhprp";
      };
    };
    "spdx-exceptions-2.1.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.1.0.tgz";
        sha512 = "057m2ab3y8j38xb89w7d191hfaa693vbf7wnwkf302zicsgi2v5ayvcc4f03vyj4yyycqasqp3ryp2d3q0vcaq54r4ls2g5dar4vbg0";
      };
    };
    "spdx-expression-parse-3.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.0.tgz";
        sha512 = "351djgqvsgqmfg6h764c2k09dmixczw5073jirm8km6i1yym4xjrzc7g5ckwkidi3gls7s910m4ahl8sh37dsb478j8j3sigbfq63k2";
      };
    };
    "spdx-license-ids-3.0.0" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.0.tgz";
        sha512 = "066gb8vcffv2mf3lbmxvxp5b60jviw32x52n50l3zgl9z4cgwg74ca4kr4y5c3mss736bmg9nxl1lvprishbikqy0jy56770v10zqfv";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sshpk-1.14.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.1.tgz";
        sha1 = "130f5975eddad963f1d56f92b9ac6c51fa9f83eb";
      };
    };
    "ssri-5.3.0" = {
      name = "ssri";
      packageName = "ssri";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssri/-/ssri-5.3.0.tgz";
        sha512 = "00qc3iqsi21cc2az3nz36q88psab4ickpzranndk6vmrb6yhn5xsq3kgp21x3lp0406bdaalpb59xy7zzqnl40ans69v3z2l8z8h52x";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "29s1fqgr4mnhfxwczgdghfmmc1f792m9hysvcjxw2h5lfj8ndf2b6gm02m96qk5m75g4aisijvng4pk618anwbr8i9ay2jyszkqgslw";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "315yd4vzwrwk3vwj1klf46y1cj2jbvf88066y2rnwhksb98phj46jkxixbwsp3h607w7czy7cby522s7sx8mvspdpdm3s72y2ga3x4z";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha1 = "3c531942e908c2697c0ec344858c286c7ca0a60a";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-4.4.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-4.4.0.tgz";
        sha512 = "1flwwfdd7gg94xrc0b2ard3qjx4cpy600q49gx43y8pzvs7j56q78bjhv8mk18vgbggr4fd11jda8ck5cdrkc5jcjs04nlp7kwbg85c";
      };
    };
    "supports-color-5.3.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.3.0.tgz";
        sha512 = "0v9skvg8c5hgqfsm98p7d7hisk11syjdvl3nxid3ik572hbjwv4vyzws7q0n1yz8mvb1asbk00838fi09hyfskrng54icn8nbag98yi";
      };
    };
    "table-4.0.2" = {
      name = "table";
      packageName = "table";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/table/-/table-4.0.2.tgz";
        sha512 = "2q47avrxblc0an2g5ij8sd7ss2bqhdxy2949dk774gyg9vmsivg7fwyn885v2va72sxiv5k59ifvi3hg4ra6z95lr8in6sjyw008jai";
      };
    };
    "tar-3.1.15" = {
      name = "tar";
      packageName = "tar";
      version = "3.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-3.1.15.tgz";
        sha512 = "1ryql8hyrrhd0gdd71ishbj3cnr8ay0i0wpvy9mj3hjiy35cc1wa0h07wz8jwils98j00gr03ix3cf2j1xm43xjn9bsavwn1yr4a0x5";
      };
    };
    "temp-0.8.3" = {
      name = "temp";
      packageName = "temp";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.8.3.tgz";
        sha1 = "e0c6bc4d26b903124410e4fed81103014dfc1f59";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "0drg2bck1cj8677rgs1l98v7vqaxawcqh6ja87qilwnd719l5y0lzv5ssn3pcwa37fdbg4188y6x15a90vkllyvfpd9v7fai2b8j44d";
      };
    };
    "tough-cookie-2.3.4" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.4.tgz";
        sha512 = "0ncm6j3cjq1f26mzjf04k9bkw1b08w53s4qa3a11c1bdj4pgnqv1422c1xs5jyy6y1psppjx52fhagq5zkjkgrcpdkxcdiry96r77jd";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "uid-number-0.0.5" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.5.tgz";
        sha1 = "5a3db23ef5dbd55b81fce0ec9a2ac6fccdebb81e";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "validate-npm-package-license-3.0.3" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.3.tgz";
        sha512 = "39caf21ga6s2gvpka90wdngdijarwmkix5fpgh9r94bw14fx1zfnf7j5mprgsdlh8dv0wpwxn65qn9gfwa8n3dxw3iqaj7qf994wxpb";
      };
    };
    "validate-npm-package-name-3.0.0" = {
      name = "validate-npm-package-name";
      packageName = "validate-npm-package-name";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-3.0.0.tgz";
        sha1 = "5fa912d81eb7d0c74afc140de7317f0ca7df437e";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "walk-2.3.13" = {
      name = "walk";
      packageName = "walk";
      version = "2.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/walk/-/walk-2.3.13.tgz";
        sha512 = "2g4ayyccqgq4fx68dhds9pwhvj2344n9p0lhb4z1hnsi882apm64s434lqz57rx4b0r1x9w1njfqrywd1la0ljqm7j4xxg8nixqri7g";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha512 = "358cfi3qak701qp5pwkq47n87ca4m8k4lvjl0pdybvmp92nwwd7azzhahy9gy3kg8lqrqdry9l6pl2csflzr0nvwnc3p6asjyi6khn5";
      };
    };
    "wide-align-1.1.2" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.2.tgz";
        sha512 = "39m5b8qc31vxhh0bz14vh9a1kf9znarvlpkf0v6vv1f2dxi61gihav2djq2mn7ns1z3yq6l8pyydj52fyzbm2q04rssrcrv4jbwnc4a";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "write-0.2.1" = {
      name = "write";
      packageName = "write";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/write/-/write-0.2.1.tgz";
        sha1 = "5fc03828e264cea3fe91455476f7a3c566cb0757";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "yallist-3.0.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.0.2.tgz";
        sha1 = "8452b4bb7e83c7c188d8041c1a837c773d6d8bb9";
      };
    };
  };
in
{
  mocha = nodeEnv.buildNodePackage {
    name = "mocha";
    packageName = "mocha";
    version = "5.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/mocha/-/mocha-5.0.5.tgz";
      sha512 = "20cyp9x4b3gfrd50w8dcfkm0dv2mc6z0ikvfpkc8dzca6hppslgn0yiw2qdzc4ggf234kzcdvs0hw7lnv7ywilaml4w39vr6r93ghyw";
    };
    dependencies = [
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."browser-stdout-1.3.1"
      sources."commander-2.11.0"
      sources."concat-map-0.0.1"
      sources."debug-3.1.0"
      sources."diff-3.5.0"
      sources."escape-string-regexp-1.0.5"
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.2"
      sources."growl-1.10.3"
      sources."has-flag-2.0.0"
      sources."he-1.1.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."ms-2.0.0"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."supports-color-4.4.0"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "simple, flexible, fun test framework";
      homepage = https://mochajs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  eslint = nodeEnv.buildNodePackage {
    name = "eslint";
    packageName = "eslint";
    version = "4.19.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/eslint/-/eslint-4.19.1.tgz";
      sha512 = "0hw70vjlg6z0y9kf6vjr7g0w9hbm426fwvyzr88l62c5hd9mxrbw5v34b6zb31vbbyda3mkvcwgfnxgqaxvpn0wlrxr0va43pbzygbd";
    };
    dependencies = [
      sources."acorn-5.5.3"
      (sources."acorn-jsx-3.0.1" // {
        dependencies = [
          sources."acorn-3.3.0"
        ];
      })
      sources."ajv-5.5.2"
      sources."ajv-keywords-2.1.1"
      sources."ansi-escapes-3.1.0"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."argparse-1.0.10"
      sources."array-union-1.0.2"
      sources."array-uniq-1.0.3"
      sources."arrify-1.0.1"
      (sources."babel-code-frame-6.26.0" // {
        dependencies = [
          sources."chalk-1.1.3"
          sources."strip-ansi-3.0.1"
        ];
      })
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."buffer-from-1.0.0"
      sources."caller-path-0.1.0"
      sources."callsites-0.2.0"
      (sources."chalk-2.3.2" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."supports-color-5.3.0"
        ];
      })
      sources."chardet-0.4.2"
      sources."circular-json-0.3.3"
      sources."cli-cursor-2.1.0"
      sources."cli-width-2.2.0"
      sources."co-4.6.0"
      sources."color-convert-1.9.1"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."core-util-is-1.0.2"
      sources."cross-spawn-5.1.0"
      sources."debug-3.1.0"
      sources."deep-is-0.1.3"
      sources."del-2.2.2"
      sources."doctrine-2.1.0"
      sources."escape-string-regexp-1.0.5"
      sources."eslint-scope-3.7.1"
      sources."eslint-visitor-keys-1.0.0"
      sources."espree-3.5.4"
      sources."esprima-4.0.0"
      sources."esquery-1.0.1"
      sources."esrecurse-4.2.1"
      sources."estraverse-4.2.0"
      sources."esutils-2.0.2"
      sources."external-editor-2.2.0"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."fast-levenshtein-2.0.6"
      sources."figures-2.0.0"
      sources."file-entry-cache-2.0.0"
      sources."flat-cache-1.3.0"
      sources."fs.realpath-1.0.0"
      sources."functional-red-black-tree-1.0.1"
      sources."glob-7.1.2"
      sources."globals-11.4.0"
      sources."globby-5.0.0"
      sources."graceful-fs-4.1.11"
      sources."has-ansi-2.0.0"
      sources."has-flag-3.0.0"
      sources."iconv-lite-0.4.21"
      sources."ignore-3.3.7"
      sources."imurmurhash-0.1.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."inquirer-3.3.0"
      sources."is-fullwidth-code-point-2.0.0"
      sources."is-path-cwd-1.0.0"
      sources."is-path-in-cwd-1.0.1"
      sources."is-path-inside-1.0.1"
      sources."is-promise-2.1.0"
      sources."is-resolvable-1.1.0"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."js-tokens-3.0.2"
      sources."js-yaml-3.11.0"
      sources."json-schema-traverse-0.3.1"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."levn-0.3.0"
      sources."lodash-4.17.5"
      sources."lru-cache-4.1.2"
      sources."mimic-fn-1.2.0"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."ms-2.0.0"
      sources."mute-stream-0.0.7"
      sources."natural-compare-1.4.0"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."onetime-2.0.1"
      sources."optionator-0.8.2"
      sources."os-tmpdir-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."path-is-inside-1.0.2"
      sources."pify-2.3.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      sources."pluralize-7.0.0"
      sources."prelude-ls-1.1.2"
      sources."process-nextick-args-2.0.0"
      sources."progress-2.0.0"
      sources."pseudomap-1.0.2"
      sources."readable-stream-2.3.6"
      sources."regexpp-1.1.0"
      sources."require-uncached-1.0.3"
      sources."resolve-from-1.0.1"
      sources."restore-cursor-2.0.0"
      sources."rimraf-2.6.2"
      sources."run-async-2.3.0"
      sources."rx-lite-4.0.8"
      sources."rx-lite-aggregates-4.0.8"
      sources."safe-buffer-5.1.1"
      sources."safer-buffer-2.1.2"
      sources."semver-5.5.0"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."signal-exit-3.0.2"
      sources."slice-ansi-1.0.0"
      sources."sprintf-js-1.0.3"
      sources."string-width-2.1.1"
      sources."string_decoder-1.1.1"
      (sources."strip-ansi-4.0.0" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
        ];
      })
      sources."strip-json-comments-2.0.1"
      sources."supports-color-2.0.0"
      sources."table-4.0.2"
      sources."text-table-0.2.0"
      sources."through-2.3.8"
      sources."tmp-0.0.33"
      sources."type-check-0.3.2"
      sources."typedarray-0.0.6"
      sources."util-deprecate-1.0.2"
      sources."which-1.3.0"
      sources."wordwrap-1.0.0"
      sources."wrappy-1.0.2"
      sources."write-0.2.1"
      sources."yallist-2.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An AST-based pattern checker for JavaScript.";
      homepage = https://eslint.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  node2nix = nodeEnv.buildNodePackage {
    name = "node2nix";
    packageName = "node2nix";
    version = "1.5.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/node2nix/-/node2nix-1.5.3.tgz";
      sha512 = "1nwm3hvx3ybg10mzn5sysdgxii42975v6gyrzjb79s46lhk67ndf1fcrlrxcfaiyj9a997hz2zk9ysm0qclxsd5nziwm01myv95z262";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      sources."ajv-5.5.2"
      sources."ansi-regex-2.1.1"
      sources."aproba-1.2.0"
      sources."are-we-there-yet-1.1.4"
      sources."asn1-0.2.3"
      sources."assert-plus-1.0.0"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.7.0"
      sources."base64-js-1.2.3"
      sources."bcrypt-pbkdf-1.0.1"
      sources."boom-4.3.1"
      sources."buffer-from-1.0.0"
      sources."builtin-modules-1.1.1"
      sources."builtins-1.0.3"
      sources."caseless-0.12.0"
      sources."co-4.6.0"
      sources."code-point-at-1.1.0"
      sources."combined-stream-1.0.6"
      sources."concat-stream-1.6.2"
      sources."config-chain-1.1.11"
      sources."console-control-strings-1.1.0"
      sources."core-util-is-1.0.2"
      (sources."cryptiles-3.1.2" // {
        dependencies = [
          sources."boom-5.2.0"
        ];
      })
      sources."dashdash-1.14.1"
      sources."delayed-stream-1.0.0"
      sources."delegates-1.0.0"
      sources."ecc-jsbn-0.1.1"
      sources."extend-3.0.1"
      sources."extsprintf-1.3.0"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."findit-2.0.0"
      sources."foreachasync-3.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.2"
      sources."fs-extra-0.6.4"
      (sources."fs.extra-1.3.2" // {
        dependencies = [
          sources."mkdirp-0.3.5"
        ];
      })
      sources."gauge-2.7.4"
      sources."getpass-0.1.7"
      sources."graceful-fs-4.1.11"
      sources."har-schema-2.0.0"
      sources."har-validator-5.0.3"
      sources."has-unicode-2.0.1"
      sources."hawk-6.0.2"
      sources."hoek-4.2.1"
      sources."hosted-git-info-2.6.0"
      sources."http-signature-1.2.0"
      sources."inherits-2.0.3"
      sources."ini-1.3.5"
      sources."is-builtin-module-1.0.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."is-typedarray-1.0.0"
      sources."isarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.3.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonfile-1.0.1"
      sources."jsprim-1.4.1"
      sources."mime-db-1.33.0"
      sources."mime-types-2.1.18"
      sources."minimist-0.0.8"
      sources."minipass-2.2.4"
      sources."minizlib-1.1.0"
      sources."mkdirp-0.5.1"
      sources."ncp-0.4.2"
      sources."nijs-0.0.25"
      sources."nopt-3.0.6"
      sources."normalize-package-data-2.4.0"
      sources."npm-package-arg-6.1.0"
      sources."npm-registry-client-8.5.1"
      (sources."npmconf-2.1.2" // {
        dependencies = [
          sources."once-1.3.3"
          sources."semver-4.3.6"
        ];
      })
      sources."npmlog-4.1.2"
      sources."number-is-nan-1.0.1"
      sources."oauth-sign-0.8.2"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."optparse-1.0.5"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."osenv-0.1.5"
      sources."performance-now-2.1.0"
      sources."process-nextick-args-2.0.0"
      sources."proto-list-1.2.4"
      sources."punycode-1.4.1"
      sources."qs-6.5.1"
      sources."readable-stream-2.3.6"
      sources."request-2.85.0"
      sources."retry-0.10.1"
      sources."rimraf-2.2.8"
      sources."safe-buffer-5.1.1"
      sources."semver-5.5.0"
      sources."set-blocking-2.0.0"
      sources."signal-exit-3.0.2"
      sources."slasp-0.0.4"
      sources."slide-1.1.6"
      sources."sntp-2.1.0"
      sources."spdx-correct-3.0.0"
      sources."spdx-exceptions-2.1.0"
      sources."spdx-expression-parse-3.0.0"
      sources."spdx-license-ids-3.0.0"
      sources."sshpk-1.14.1"
      sources."ssri-5.3.0"
      sources."string-width-1.0.2"
      sources."string_decoder-1.1.1"
      sources."stringstream-0.0.5"
      sources."strip-ansi-3.0.1"
      sources."tar-3.1.15"
      sources."temp-0.8.3"
      sources."tough-cookie-2.3.4"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."typedarray-0.0.6"
      sources."uid-number-0.0.5"
      sources."util-deprecate-1.0.2"
      sources."uuid-3.2.1"
      sources."validate-npm-package-license-3.0.3"
      sources."validate-npm-package-name-3.0.0"
      sources."verror-1.10.0"
      sources."walk-2.3.13"
      sources."wide-align-1.1.2"
      sources."wrappy-1.0.2"
      sources."yallist-3.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Generate Nix expressions to build NPM packages";
      homepage = https://github.com/svanderburg/node2nix;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
}