# This file has been generated by node2nix 1.3.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "eslint-plugin-varspacing";
    packageName = "eslint-plugin-varspacing";
    version = "1.1.0";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      description = "A eslint rule for proper var spacing";
      homepage = "https://github.com/Sententiaregum/eslint-plugin-varspacing#readme";
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}