# This file has been generated by node2nix 1.3.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "browser-stdout-1.3.0" = {
      name = "browser-stdout";
      packageName = "browser-stdout";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-stdout/-/browser-stdout-1.3.0.tgz";
        sha1 = "f351d32969d32fa5d7a5567154263d928ae3bd1f";
      };
    };
    "commander-2.11.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.11.0.tgz";
        sha512 = "2yi2hwf0bghfnv1fdgd4wvh7s0acjrgqbgww97ncm6i6s6ffs1zahnj48f6gqpqj6fsf0jigvnr0civ25k2160c38281r80wvg7jkkg";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "diff-3.3.1" = {
      name = "diff";
      packageName = "diff";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-3.3.1.tgz";
        sha512 = "31pj7v5gg5igmvwzk6zxw1wbvwjg6m9sfl0h3bs1x4q6idcw98vr8z8wcqk2603q0blpqkmkxp659kjj91wksr03yr8xlh16djcg8rh";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "growl-1.10.3" = {
      name = "growl";
      packageName = "growl";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/growl/-/growl-1.10.3.tgz";
        sha512 = "3aibvz85l13j140w4jjdk8939q6r7dnf8ay2licxgkaaldk7wbm093c1p5g7k5cg80rl0xslmczyraawfgdr82hhxn7rfsm1rn6rac4";
      };
    };
    "he-1.1.1" = {
      name = "he";
      packageName = "he";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.1.1.tgz";
        sha1 = "93410fd21b009735151f8868c2f271f3427e23fd";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "supports-color-4.4.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-4.4.0.tgz";
        sha512 = "1flwwfdd7gg94xrc0b2ard3qjx4cpy600q49gx43y8pzvs7j56q78bjhv8mk18vgbggr4fd11jda8ck5cdrkc5jcjs04nlp7kwbg85c";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "has-flag-2.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz";
        sha1 = "e8207af1cc7b30d446cc70b734b5e8be18f88d51";
      };
    };
    "ajv-5.2.3" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.2.3.tgz";
        sha1 = "c06f598778c44c6b161abafe3466b81ad1814ed2";
      };
    };
    "babel-code-frame-6.26.0" = {
      name = "babel-code-frame";
      packageName = "babel-code-frame";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.26.0.tgz";
        sha1 = "63fd43f7dc1e3bb7ce35947db8fe369a3f58c74b";
      };
    };
    "chalk-2.2.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.2.0.tgz";
        sha512 = "3vfffivwlp2hr7dwh84lvayba94a98ddhb8dwkv14magmfdj1n895880sik7liqv4xgnvvpr2v5jsm1gzl1fypl7nl9dpa6d3zhq4yh";
      };
    };
    "concat-stream-1.6.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.0.tgz";
        sha1 = "0aac662fd52be78964d5532f694784e70110acf7";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "doctrine-2.0.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-2.0.0.tgz";
        sha1 = "c73d8d2909d22291e1a007a395804da8b665fe63";
      };
    };
    "eslint-scope-3.7.1" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-3.7.1.tgz";
        sha1 = "3d63c3edfda02e06e01a452ad88caacc7cdcb6e8";
      };
    };
    "espree-3.5.1" = {
      name = "espree";
      packageName = "espree";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.5.1.tgz";
        sha1 = "0c988b8ab46db53100a1954ae4ba995ddd27d87e";
      };
    };
    "esquery-1.0.0" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.0.0.tgz";
        sha1 = "cfba8b57d7fba93f17298a8a006a04cda13d80fa";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "file-entry-cache-2.0.0" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-2.0.0.tgz";
        sha1 = "c392990c3e684783d838b8c84a45d8a048458361";
      };
    };
    "functional-red-black-tree-1.0.1" = {
      name = "functional-red-black-tree";
      packageName = "functional-red-black-tree";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz";
        sha1 = "1b0ab3bd553b2a0d6399d29c0e3ea0b252078327";
      };
    };
    "globals-9.18.0" = {
      name = "globals";
      packageName = "globals";
      version = "9.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-9.18.0.tgz";
        sha512 = "18psd5ig23apaw07k4mma3z1hi2ndfwsqkm05hxashnf5lf7mpfs6kjiircc0x3x3q15j2x2j4zfzsqacxvfsmw40zjchn44bfccjab";
      };
    };
    "ignore-3.3.5" = {
      name = "ignore";
      packageName = "ignore";
      version = "3.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-3.3.5.tgz";
        sha512 = "07qdg1b3fwg8b7zwq83rljcx2h0ybq8s43h5xkvsr252qij7ib2gcjamqsb25zv1nvxm94yrvf4fl41s1kyms8zhr86cspwcbggvc94";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inquirer-3.3.0" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-3.3.0.tgz";
        sha512 = "1wsmzzva3rfjb4bfks7ba2nvha9ziwgq2kag6xxibc5cc6mz19xbgj4fm3a7ghvfbfx4am0x13ibc8j2s5m3sv12nph44rq56gnvv47";
      };
    };
    "is-resolvable-1.0.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.0.0.tgz";
        sha1 = "8df57c61ea2e3c501408d100fb013cf8d6e0cc62";
      };
    };
    "js-yaml-3.10.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.10.0.tgz";
        sha512 = "0h26sq1bwxc45bm0hvlcadrbk4bizzaw729wvw690ya7mpys45bqfzdqwhjkdrnq0i44dzxckykz4bix22jfdyfg1asybg3yzczjsrv";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "path-is-inside-1.0.2" = {
      name = "path-is-inside";
      packageName = "path-is-inside";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-inside/-/path-is-inside-1.0.2.tgz";
        sha1 = "365417dede44430d1c11af61027facf074bdfc53";
      };
    };
    "pluralize-7.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-7.0.0.tgz";
        sha512 = "2ihaln20qjx82jx73wgzirbyp8mfmhxr75am1h0w8n5hy2gsbgvw9dricv7h57ycxzax84bma96wjscmdszs5mr2lsyxpfjvhwl2601";
      };
    };
    "progress-2.0.0" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.0.tgz";
        sha1 = "8a1be366bf8fc23db2bd23f10c6fe920b4389d1f";
      };
    };
    "require-uncached-1.0.3" = {
      name = "require-uncached";
      packageName = "require-uncached";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-uncached/-/require-uncached-1.0.3.tgz";
        sha1 = "4e0d56d6c9662fd31e43011c4b95aa49955421d3";
      };
    };
    "semver-5.4.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.4.1.tgz";
        sha512 = "2r13vwvb5ick34k6flr7vgbjfsdka8zbj5a74rd0ba4bp0nqmhppbaw3qlwn7f4smpifpa4iy4hxj137y598rbvsmy3h0d8vxgvzwar";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha1 = "3c531942e908c2697c0ec344858c286c7ca0a60a";
      };
    };
    "table-4.0.2" = {
      name = "table";
      packageName = "table";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/table/-/table-4.0.2.tgz";
        sha512 = "2q47avrxblc0an2g5ij8sd7ss2bqhdxy2949dk774gyg9vmsivg7fwyn885v2va72sxiv5k59ifvi3hg4ra6z95lr8in6sjyw008jai";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "fast-deep-equal-1.0.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.0.0.tgz";
        sha1 = "96256a3bc975595eb36d82e9929d060d893439ff";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-3.2.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.0.tgz";
        sha512 = "2x19fs1qvg7ifsdvii4g8kqpa5hir1lm0k0y0fz6dhm5c8gh4z9il4wqczl078p2ikmrav23dmj86cxy8y1j22k4mv59d8qq6c8wx1n";
      };
    };
    "supports-color-4.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-4.5.0.tgz";
        sha1 = "be7a0de484dec5c5cddf8b3d59125044912f635b";
      };
    };
    "color-convert-1.9.0" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.0.tgz";
        sha1 = "1accf97dd739b983bf994d56fec8f95853641b7a";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.3.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz";
        sha512 = "1wlizkv2wnz2nyb0lfxgs1m27zzcvasp3n5cfrd7hm4ch1wn79df2nbhzfadba5qqdfb28vhmw3drhp46vk2q6xk524qagvr76v7slv";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha512 = "22vw5mmwlyblqc2zyqwl39wyhyahhpiyknim8iz5fk6xi002x777gkswiq8fh297djs5ii4pgrys57wq33hr5zf3xfd0d7kjxkzl0g0";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "lru-cache-4.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.1.tgz";
        sha512 = "1xz91sizgyzh8plz5jx1labzpygapm6xy3qpxriaj00yvnhy4lnmhqcb20qln4lh80c5g3yzp4j5i6g63njq1r5sl9c0zlkh9xjk2xb";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha512 = "358cfi3qak701qp5pwkq47n87ca4m8k4lvjl0pdybvmp92nwwd7azzhahy9gy3kg8lqrqdry9l6pl2csflzr0nvwnc3p6asjyi6khn5";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "esrecurse-4.2.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.2.0.tgz";
        sha1 = "fa9568d98d3823f9a41d91e902dcab9ea6e5b163";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "acorn-5.1.2" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.1.2.tgz";
        sha512 = "1cgdl1g9g05iz6r09i0hmf78cmjca2yafazwaj202w9dck00b7jnmyk4l27ackxy13g4g4ay6vkf6glh18wm29vpmjqsga1n9j8bpm3";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "flat-cache-1.3.0" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-1.3.0.tgz";
        sha1 = "d3030b32b38154f4e3b7e9c709f490f7ef97c481";
      };
    };
    "circular-json-0.3.3" = {
      name = "circular-json";
      packageName = "circular-json";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/circular-json/-/circular-json-0.3.3.tgz";
        sha512 = "3hadrrn41znfv3gbqjxf0ckzjmns7w7zgsqw73sdz8nclaff9b0cg1mqhz3zxw3ndnmqqvrdcfykkfpv2v1pv4jdyzcccbn3hsbg4ji";
      };
    };
    "del-2.2.2" = {
      name = "del";
      packageName = "del";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/del/-/del-2.2.2.tgz";
        sha1 = "c12c981d067846c84bcaf862cff930d907ffd1a8";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "write-0.2.1" = {
      name = "write";
      packageName = "write";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/write/-/write-0.2.1.tgz";
        sha1 = "5fc03828e264cea3fe91455476f7a3c566cb0757";
      };
    };
    "globby-5.0.0" = {
      name = "globby";
      packageName = "globby";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-5.0.0.tgz";
        sha1 = "ebd84667ca0dbb330b99bcfc68eac2bc54370e0d";
      };
    };
    "is-path-cwd-1.0.0" = {
      name = "is-path-cwd";
      packageName = "is-path-cwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-cwd/-/is-path-cwd-1.0.0.tgz";
        sha1 = "d225ec23132e89edd38fda767472e62e65f1106d";
      };
    };
    "is-path-in-cwd-1.0.0" = {
      name = "is-path-in-cwd";
      packageName = "is-path-in-cwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-in-cwd/-/is-path-in-cwd-1.0.0.tgz";
        sha1 = "6477582b8214d602346094567003be8a9eac04dc";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "array-union-1.0.2" = {
      name = "array-union";
      packageName = "array-union";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz";
        sha1 = "9a34410e4f4e3da23dea375be5be70f24778ec39";
      };
    };
    "arrify-1.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
        sha1 = "898508da2226f380df904728456849c1501a4b0d";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "is-path-inside-1.0.0" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.0.tgz";
        sha1 = "fc06e5a1683fbda13de667aff717bbc10a48f37f";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "ansi-escapes-3.0.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-3.0.0.tgz";
        sha512 = "06szfav8g7xywvqsis16nnkjqs2snhv37r4m53l1ax8k2sahvqv9id2klam32jajqd08ylw8g9wbcjr971igx6vh8idan76drrjby9v";
      };
    };
    "cli-cursor-2.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-2.1.0.tgz";
        sha1 = "b35dac376479facc3e94747d41d0d0f5238ffcb5";
      };
    };
    "cli-width-2.2.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-2.2.0.tgz";
        sha1 = "ff19ede8a9a5e579324147b0c11f0fbcbabed639";
      };
    };
    "external-editor-2.0.5" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-2.0.5.tgz";
        sha512 = "3znpqavb7rxmw74p6hnq963agimzsm5r524jrpy9v6sbbhbbk77qhklgkr65jirq0a58lsz8jgvwy9q4wfmwl7ahj6nzrckhpmyij1j";
      };
    };
    "figures-2.0.0" = {
      name = "figures";
      packageName = "figures";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-2.0.0.tgz";
        sha1 = "3ab1a2d2a62c8bfb431a0c94cb797a2fce27c962";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "run-async-2.3.0" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.3.0.tgz";
        sha1 = "0371ab4ae0bdd720d4166d7dfda64ff7a445a6c0";
      };
    };
    "rx-lite-4.0.8" = {
      name = "rx-lite";
      packageName = "rx-lite";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx-lite/-/rx-lite-4.0.8.tgz";
        sha1 = "0b1e11af8bc44836f04a6407e92da42467b79444";
      };
    };
    "rx-lite-aggregates-4.0.8" = {
      name = "rx-lite-aggregates";
      packageName = "rx-lite-aggregates";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx-lite-aggregates/-/rx-lite-aggregates-4.0.8.tgz";
        sha1 = "753b87a89a11c95467c4ac1626c4efc4e05c67be";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "29s1fqgr4mnhfxwczgdghfmmc1f792m9hysvcjxw2h5lfj8ndf2b6gm02m96qk5m75g4aisijvng4pk618anwbr8i9ay2jyszkqgslw";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "restore-cursor-2.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-2.0.0.tgz";
        sha1 = "9f7ee287f82fd326d4fd162923d62129eee0dfaf";
      };
    };
    "onetime-2.0.1" = {
      name = "onetime";
      packageName = "onetime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-2.0.1.tgz";
        sha1 = "067428230fd67443b2794b22bba528b6867962d4";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "mimic-fn-1.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-1.1.0.tgz";
        sha1 = "e667783d92e89dbd342818b5230b9d62a672ad18";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "jschardet-1.5.1" = {
      name = "jschardet";
      packageName = "jschardet";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jschardet/-/jschardet-1.5.1.tgz";
        sha512 = "3c44v9rz6j4z6i7gj2v3wmfcqv5i47psysgd1p4jcgz114vfk99fif1n1r08jbsdkp4g3smv1wx7x4ikwa7q9dp5i1bc77la17s2kdw";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "0drg2bck1cj8677rgs1l98v7vqaxawcqh6ja87qilwnd719l5y0lzv5ssn3pcwa37fdbg4188y6x15a90vkllyvfpd9v7fai2b8j44d";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "is-promise-2.1.0" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz";
        sha1 = "79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "tryit-1.0.3" = {
      name = "tryit";
      packageName = "tryit";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tryit/-/tryit-1.0.3.tgz";
        sha1 = "393be730a9446fd1ead6da59a014308f36c289cb";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "esprima-4.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.0.tgz";
        sha512 = "27mkhd94y9vrr8pb97br0ym5h85rawwb0biswgwdfp31x0387y12k9p9598bi4fc83fif6crfzqiqmmjs4x7gcb22ml3z1fldqm7yx1";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "caller-path-0.1.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-0.1.0.tgz";
        sha1 = "94085ef63581ecd3daa92444a8fe94e82577751f";
      };
    };
    "resolve-from-1.0.1" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-1.0.1.tgz";
        sha1 = "26cbfe935d1aeeeabb29bc3fe5aeb01e93d44226";
      };
    };
    "callsites-0.2.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-0.2.0.tgz";
        sha1 = "afab96262910a7f33c19a5775825c69f34e350ca";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ajv-keywords-2.1.0" = {
      name = "ajv-keywords";
      packageName = "ajv-keywords";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-2.1.0.tgz";
        sha1 = "a296e17f7bfae7c1ce4f7e0de53d29cb32162df0";
      };
    };
    "slice-ansi-1.0.0" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-1.0.0.tgz";
        sha512 = "1xd3zsk02nck4y601rn98n8cicrphaw5bdix278mk1yizmjv9s0wpa6akcqggd7d99c55s3byf4ylqdxkshyfsfnfx7lvwbmq2b3siw";
      };
    };
  };
in
{
  mocha = nodeEnv.buildNodePackage {
    name = "mocha";
    packageName = "mocha";
    version = "4.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/mocha/-/mocha-4.0.1.tgz";
      sha512 = "07hbr2w894az0s1hi6lglls00nwb941ymwm580q4917kwcmsg3ngagqf9cfxyjdwwivm956dpwzsrkbk4i7a404i56w1y809a3fdw3s";
    };
    dependencies = [
      sources."browser-stdout-1.3.0"
      sources."commander-2.11.0"
      sources."debug-3.1.0"
      sources."diff-3.3.1"
      sources."escape-string-regexp-1.0.5"
      sources."glob-7.1.2"
      sources."growl-1.10.3"
      sources."he-1.1.1"
      sources."mkdirp-0.5.1"
      sources."supports-color-4.4.0"
      sources."ms-2.0.0"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.8"
      sources."balanced-match-1.0.0"
      sources."concat-map-0.0.1"
      sources."minimist-0.0.8"
      sources."has-flag-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "simple, flexible, fun test framework";
      homepage = https://mochajs.org/;
      license = "MIT";
    };
    production = true;
  };
  eslint = nodeEnv.buildNodePackage {
    name = "eslint";
    packageName = "eslint";
    version = "4.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/eslint/-/eslint-4.9.0.tgz";
      sha1 = "76879d274068261b191fe0f2f56c74c2f4208e8b";
    };
    dependencies = [
      sources."ajv-5.2.3"
      (sources."babel-code-frame-6.26.0" // {
        dependencies = [
          sources."chalk-1.1.3"
          sources."strip-ansi-3.0.1"
        ];
      })
      (sources."chalk-2.2.0" // {
        dependencies = [
          sources."ansi-styles-3.2.0"
          sources."supports-color-4.5.0"
        ];
      })
      sources."concat-stream-1.6.0"
      sources."cross-spawn-5.1.0"
      sources."debug-3.1.0"
      sources."doctrine-2.0.0"
      sources."eslint-scope-3.7.1"
      sources."espree-3.5.1"
      sources."esquery-1.0.0"
      sources."estraverse-4.2.0"
      sources."esutils-2.0.2"
      sources."file-entry-cache-2.0.0"
      sources."functional-red-black-tree-1.0.1"
      sources."glob-7.1.2"
      sources."globals-9.18.0"
      sources."ignore-3.3.5"
      sources."imurmurhash-0.1.4"
      sources."inquirer-3.3.0"
      sources."is-resolvable-1.0.0"
      sources."js-yaml-3.10.0"
      sources."json-stable-stringify-1.0.1"
      sources."levn-0.3.0"
      sources."lodash-4.17.4"
      sources."minimatch-3.0.4"
      sources."mkdirp-0.5.1"
      sources."natural-compare-1.4.0"
      sources."optionator-0.8.2"
      sources."path-is-inside-1.0.2"
      sources."pluralize-7.0.0"
      sources."progress-2.0.0"
      sources."require-uncached-1.0.3"
      sources."semver-5.4.1"
      (sources."strip-ansi-4.0.0" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
        ];
      })
      sources."strip-json-comments-2.0.1"
      sources."table-4.0.2"
      sources."text-table-0.2.0"
      sources."co-4.6.0"
      sources."fast-deep-equal-1.0.0"
      sources."json-schema-traverse-0.3.1"
      sources."js-tokens-3.0.2"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."color-convert-1.9.0"
      sources."color-name-1.1.3"
      sources."has-flag-2.0.0"
      sources."inherits-2.0.3"
      sources."typedarray-0.0.6"
      sources."readable-stream-2.3.3"
      sources."core-util-is-1.0.2"
      sources."isarray-1.0.0"
      sources."process-nextick-args-1.0.7"
      sources."safe-buffer-5.1.1"
      sources."string_decoder-1.0.3"
      sources."util-deprecate-1.0.2"
      sources."lru-cache-4.1.1"
      sources."shebang-command-1.2.0"
      sources."which-1.3.0"
      sources."pseudomap-1.0.2"
      sources."yallist-2.1.2"
      sources."shebang-regex-1.0.0"
      sources."isexe-2.0.0"
      sources."ms-2.0.0"
      sources."esrecurse-4.2.0"
      sources."object-assign-4.1.1"
      sources."acorn-5.1.2"
      (sources."acorn-jsx-3.0.1" // {
        dependencies = [
          sources."acorn-3.3.0"
        ];
      })
      sources."flat-cache-1.3.0"
      sources."circular-json-0.3.3"
      sources."del-2.2.2"
      sources."graceful-fs-4.1.11"
      sources."write-0.2.1"
      sources."globby-5.0.0"
      sources."is-path-cwd-1.0.0"
      sources."is-path-in-cwd-1.0.0"
      sources."pify-2.3.0"
      sources."pinkie-promise-2.0.1"
      sources."rimraf-2.6.2"
      sources."array-union-1.0.2"
      sources."arrify-1.0.1"
      sources."array-uniq-1.0.3"
      sources."is-path-inside-1.0.0"
      sources."pinkie-2.0.4"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."ansi-escapes-3.0.0"
      sources."cli-cursor-2.1.0"
      sources."cli-width-2.2.0"
      sources."external-editor-2.0.5"
      sources."figures-2.0.0"
      sources."mute-stream-0.0.7"
      sources."run-async-2.3.0"
      sources."rx-lite-4.0.8"
      sources."rx-lite-aggregates-4.0.8"
      sources."string-width-2.1.1"
      sources."through-2.3.8"
      sources."restore-cursor-2.0.0"
      sources."onetime-2.0.1"
      sources."signal-exit-3.0.2"
      sources."mimic-fn-1.1.0"
      sources."iconv-lite-0.4.19"
      sources."jschardet-1.5.1"
      sources."tmp-0.0.33"
      sources."os-tmpdir-1.0.2"
      sources."is-promise-2.1.0"
      sources."is-fullwidth-code-point-2.0.0"
      sources."tryit-1.0.3"
      sources."argparse-1.0.9"
      sources."esprima-4.0.0"
      sources."sprintf-js-1.0.3"
      sources."jsonify-0.0.0"
      sources."prelude-ls-1.1.2"
      sources."type-check-0.3.2"
      sources."brace-expansion-1.1.8"
      sources."balanced-match-1.0.0"
      sources."concat-map-0.0.1"
      sources."minimist-0.0.8"
      sources."deep-is-0.1.3"
      sources."wordwrap-1.0.0"
      sources."fast-levenshtein-2.0.6"
      sources."caller-path-0.1.0"
      sources."resolve-from-1.0.1"
      sources."callsites-0.2.0"
      sources."ajv-keywords-2.1.0"
      sources."slice-ansi-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An AST-based pattern checker for JavaScript.";
      homepage = https://eslint.org/;
      license = "MIT";
    };
    production = true;
  };
}